
version: "3.1" 

services:
 maria :
    image: docker.io/bitnami/mariadb:10.6
    container_name: meettro-db
    hostname: meettro-db 
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=meettro123!!
      - MARIADB_USER=admin
      - MARIADB_DATABASE=meettro
      - MARIADB_PASSWORD=meettro123!!
    networks:
      - backend
    restart: always

networks:
  backend: